# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c164755d2b6168ae77160ad0ab4d41ff7d58aa2eab6527f58e882df4edddb61b37b8731a75f4481c60caba9c0075adaf9b9542e4935d2b86674431a9de49dcc1

test:
  secret_key_base: a06b2dfad5bad76024d67e5de133796905ad7bc3bc746a88a6f80dfec1d76180e609340acc9e664819ec41499ffb64a25133ac9fb7b18abd81235c5a3fe25ce5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
